[package]
name = "grid_search_maze"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
grid_2d = "0.14"
rand = "0.7"
rand_isaac = { version = "0.2", features = ["serde1"] }
